name: Verify Formatting

on:
  - pull_request
  - push

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Cargo And Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          components: cargo, clippy

      - name: Cache Cargo Stuff
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Clippy
        run: cargo clippy
