name: Verify Formatting

on:
  - pull_request
  - push

jobs:
  verify-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Cargo And RustFMT
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          components: cargo, rustfmt

      - name: Verify That The Code Is Formatted
        run: cargo +nightly fmt --check
